# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/igadmin/test/fbs2mpeg_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_fbs2mpeg(object):
    def setupUi(self, fbs2mpeg):
        fbs2mpeg.setObjectName("fbs2mpeg")
        fbs2mpeg.resize(455, 661)
        self.centralwidget = QtWidgets.QWidget(fbs2mpeg)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_input_files = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_input_files.sizePolicy().hasHeightForWidth())
        self.lbl_input_files.setSizePolicy(sizePolicy)
        self.lbl_input_files.setMinimumSize(QtCore.QSize(260, 35))
        self.lbl_input_files.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lbl_input_files.setObjectName("lbl_input_files")
        self.horizontalLayout.addWidget(self.lbl_input_files)
        self.btn_input_files = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(85)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.btn_input_files.sizePolicy().hasHeightForWidth())
        self.btn_input_files.setSizePolicy(sizePolicy)
        self.btn_input_files.setMinimumSize(QtCore.QSize(85, 35))
        self.btn_input_files.setMaximumSize(QtCore.QSize(85, 35))
        self.btn_input_files.setObjectName("btn_input_files")
        self.horizontalLayout.addWidget(self.btn_input_files)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_output_path = QtWidgets.QLabel(self.centralwidget)
        self.lbl_output_path.setMinimumSize(QtCore.QSize(260, 35))
        self.lbl_output_path.setObjectName("lbl_output_path")
        self.horizontalLayout_2.addWidget(self.lbl_output_path)
        self.btn_output_path = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(85)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.btn_output_path.sizePolicy().hasHeightForWidth())
        self.btn_output_path.setSizePolicy(sizePolicy)
        self.btn_output_path.setMinimumSize(QtCore.QSize(85, 35))
        self.btn_output_path.setMaximumSize(QtCore.QSize(85, 35))
        self.btn_output_path.setObjectName("btn_output_path")
        self.horizontalLayout_2.addWidget(self.btn_output_path)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(260, 35))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(85)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.btn_run.sizePolicy().hasHeightForWidth())
        self.btn_run.setSizePolicy(sizePolicy)
        self.btn_run.setMinimumSize(QtCore.QSize(85, 35))
        self.btn_run.setMaximumSize(QtCore.QSize(85, 35))
        self.btn_run.setObjectName("btn_run")
        self.horizontalLayout_3.addWidget(self.btn_run)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        fbs2mpeg.setCentralWidget(self.centralwidget)

        self.retranslateUi(fbs2mpeg)
        QtCore.QMetaObject.connectSlotsByName(fbs2mpeg)

    def retranslateUi(self, fbs2mpeg):
        _translate = QtCore.QCoreApplication.translate
        fbs2mpeg.setWindowTitle(_translate("fbs2mpeg", "fbs2mpeg"))
        self.lbl_input_files.setText(_translate("fbs2mpeg", "Select files"))
        self.btn_input_files.setText(_translate("fbs2mpeg", "..."))
        self.lbl_output_path.setText(_translate("fbs2mpeg", "Choose a directory to save"))
        self.btn_output_path.setText(_translate("fbs2mpeg", "..."))
        self.btn_run.setText(_translate("fbs2mpeg", "Run"))
